# Generated by Django 5.1.2 on 2025-12-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InpaintResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="inpaint/originals/")),
                ("mask_image", models.ImageField(upload_to="inpaint/masks/")),
                ("result_image", models.ImageField(upload_to="inpaint/results/")),
                ("iterations", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
